name: Express GraphQL

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.0.1
        uses: actions/setup-node@v2
        with:
          node-version: 15.0.1
      - run: npm i -g lerna
      - run: lerna bootstrap
      - run: npm run build:api
